Fix error message for 'dx.aux' length check
ERROR: Error in initFESDIA(parms = parms, gridtype = gridtype, CfluxForc = CfluxForc,  : 
  Checking 'Grid': 'dx' should be a vector of length 100 is given even when a Grid is specified of == to line 27. The check for Grid$dx checks for FESDIA$N +1 but this should be FESDIA$N I think. Given that the stop message also mentions that the length needs to be "FESDIA$N"